runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.php

- url: /teacher
  script: teacher.php

- url: /(.*\.(htm$|html$|css$|js$))
  static_files: \1
  upload: (.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: \1
  upload: (.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.*\.php$)
  script: \1

- url: /.*
  script: 404.php

skip_files:
- (xampp/.*)|
